version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps: 
      - checkout
      - run: gradle build -x test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: 
          name: regression test
          command: gradle test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test: 
          requires:
            - build
